# PROJECT2023009APP

    -- Commit

        :sparkles: feature: <> -- Código

        :lipstick: feature: Monitoramento Financeiro -- Prototipo

        :wrench: chore: <> -- Configuração

        :zap: performance: <>

        :boom: bugfix: <>

        :books: documentation: <>

    -- Dependencias

        npm install @capacitor/network
        npx capacitor sync

    -- Funcionalidade

        :sparkles: feature: Verificar conexão com a Internet